[package]
name = "inflate"
version = "0.1.0"
authors = ["Federico Builes <febuiles@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniz_oxide = "0.4.4"
